[package]
name = "galaxy-interface"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zbus = "2.2.0"
event-listener = "2.5.2"
async-std = {version = "1.11.0", features = ["attributes"]}